superprograma:
    name: Super Programa
    description: Podcast del super programa conducido por La Hormiga Atómica
    soundcloud_url: https://soundcloud.com/fake
    image_url: https://img.com/devnull/image.jpg
    timezone: America/Buenos_Aires

